### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by xixi-HZC** [Lanseria/sms-mass-platform#2]
运行发现如下错误，作者能看下嘛
Error: Cannot find module 'D:\用户目录\Downloads\sms-mass-platform-master\node_modules\bcrypt\lib\binding\bcrypt_lib.node'
Require stack:
- D:\用户目录\Downloads\sms-mass-platform-master\node_modules\bcrypt\bcrypt.js
- D:\用户目录\Downloads\sms-mass-platform-master\app\schemas\user.js
- D:\用户目录\Downloads\sms-mass-platform-master\app\models\user.js
- D:\用户目录\Downloads\sms-mass-platform-master\app\controllers\index.js
- D:\用户目录\Downloads\sms-mass-platform-master\route.js
- D:\用户目录\Downloads\sms-mass-platform-master\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\用户目录\Downloads\sms-mass-platform-master\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\用户目录\Downloads\sms-mass-platform-master\app\schemas\user.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\用户目录\Downloads\sms-mass-platform-master\app\models\user.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\用户目录\\Downloads\\sms-mass-platform-master\\node_modules\\bcrypt\\bcrypt.js',
    'D:\\用户目录\\Downloads\\sms-mass-platform-master\\app\\schemas\\user.js',
    'D:\\用户目录\\Downloads\\sms-mass-platform-master\\app\\models\\user.js',
    'D:\\用户目录\\Downloads\\sms-mass-platform-master\\app\\controllers\\index.js',
    'D:\\用户目录\\Downloads\\sms-mass-platform-master\\route.js',
    'D:\\用户目录\\Downloads\\sms-mass-platform-master\\app.js'
  ]
}

**Comment by Lanseria** [comment]
此项目已经遗弃了, 请使用其他项目
